### ISSUE TITLE
skins

### ISSUE THREAD

**Issue by TectuniX** [kuamquat940/csgoremake#1]
Salut cand adaug o arma nu mai merge serverul adica mi-l face clasic, folosesc un hlds desta gata facut nush daca e de la asta, o sa incerc si pe un server hostat sa vad dar acum cand bag o arma nu mai merge. Nu cred ca este de la sv asta gata facut ca am bagat si addons-ul lui zorken etc si merg skinurile + alte adddons-uri de la nubo si la fel merg.

**Comment by kuamquat940** [comment]
Am adaugat o "protectie" ca atunci cand skinul adaugat nu exista sau este mai mare de x caractere sa se opreasca pluginul automat. Verifica consola, ar trebui sa iti scrie ca lipseste un skin dintr-o sectiune.

**Comment by TectuniX** [comment]
Setmaster:  Unknown command enable
Connection to Steam servers successful.
   VAC secure mode is activated.
Menu item 17 added to Menus Front-End: "Plugin Cvars" from plugin "pluginmenu.amxx"
Menu item 18 added to Menus Front-End: "Plugin Commands" from plugin "pluginmenu.amxx"
Started downloading servercheck.txt
[r4ge Guard] Finished downloading servercheck.txt
[r4ge Guard] Should be opening servercheck.txt
User TectuniX (1) uses protocol 48; SteamID assigned by Steam(Native)
ERROR: couldn't open custom.hpk.

asta este tot ce imi apare in consola server-ului poti te rog frumos sa-mi scoti "protectia" si sa imi dai sma?

**Comment by kuamquat940** [comment]
"Plugin says: [CSGO Remake] You have a missing file "-" in the [SKINS] section of csgo_remake.ini ."
Cauta in csgoremake1gx.ini si modifica tot ce contine "-" in "". Nu este necesar sa pui "-", poti pune direct "".

**Comment by TectuniX** [comment]
Gata, am rezolvat :D multumesc frumos
Am si eu o intrebare daca sterg liniile astea
"misc/ctwingo.wav"
"misc/twingo.wav"
afecteaza cu ceva? adica nu are cu ce, vreau sa nu-mi mai cante melodiile alea doua pentru ca mi se baga peste mvp sound "/mvp".

**Comment by kuamquat940** [comment]
Pentru asta trebuie sa stergi urmatoarele:
new g_szTWin[]
new g_szCTWin[]
apoi din public plugin_precache:
precache_sound(g_szTWin);
precache_sound(g_szCTWin);
si apoi din public-urile: public ev_RoundWon_T() si public ev_RoundWon_CT()
client_cmd(0, "spk ^"%s^"", g_szTWin);
client_cmd(0, "spk ^"%s^"", g_szCTWin);
