### ISSUE TITLE
Probleme Sursa CSGOREMAKE NUBO

### ISSUE THREAD

**Issue by ZipHaS** [kuamquat940/csgoremake#2]
Salutare!
Tocmai verificasem si eu ce ai lucrat,in primul rand felicitari pentru munca depusa, trebuia mai bine sa o vinzi pe parale... parerea mea.
-Incercam sa bag cateva skin-uri in csgoremake1gx.ini,dar imi da eroare in consola de la gamecp (Folosesc Linux pe REHLDS)
06/01/2020 - 06:23:31: AMXX] Plugin ("csgoremake1gx.amxx") is setting itself as failed.

am pus asa -> "28" "AK47 Cartel" "models/csgo/ak47_cartel.mdl" "c" "77" "12000"
06/01/2020 - 06:23:31: [AMXX] Plugin says: [CSGO Remake] You have a missing file "c" in the [SKINS] section of csgo_remake.ini .
06/01/2020 - 06:23:31: [AMXX] Run time error 1 (plugin "csgoremake1gx.amxx") - forced exit

Daca mi-ai putea raspunde sau pe discord -> Zip#4080

**Comment by kuamquat940** [comment]
#1 Dupa cum ti-a spus si baiatul de pe extream, a avut aceeasi problema. Nu ai facut lista bine si de aceea. Daca nu doresti modelul p_ trebuie sa pui doar ghilimelele **""** in loc de "-" sau spatiu gol.
