### ISSUE TITLE
Warmup

### ISSUE THREAD

**Issue by TectuniX** [kuamquat940/csgoremake#3]
Salut, ai putea sa imi scoti si mie warmup ul din sursa te rog? Si sa imi dai sursa? As dori sa nu mai fie warmup deoarece la plugin urile de vip ce iti dau automat menu cu arme daca mori in warmup, iti apare.

**Comment by kuamquat940** [comment]
Cum am scris si pe extreamcs, nu am timp sa tot modific la el. Sectiunea asta se presupune ca e pentru probleme de la mod (functii scrise gresit de mine, bug-uri si alte chestii). Contacteaza pe cineva care se pricepe sau incearca sa il modifici si singur, trebuie sa inveti scripting amxmodx pana la urma.

De data asta te ajut, dar data viitoare numai la probleme adevarate. Modifica cvar-ul asta si pune-l pe **0**, **csgor_warmup_duration**
**amx_cvar csgor_warmup_duration 0** sau in fisierul **csgoremake1gx.cfg** pune **csgor_warmup_duration 0** si reporneste serverul.
