### ISSUE TITLE
Salut

### ISSUE THREAD

**Issue by TheRealZet** [kuamquat940/csgoremake#4]
Am intampinat o problema cu modul CSGO Remake 1Gx a lui Nubo dar refacut de tine.
Problema consta in:
Vand un skin si cineva il cumpara, dar NU primesc punctele pe skinul respectiv

**Comment by kuamquat940** [comment]
O sa verific si o sa fac update la mod cu mai multe imbunatatiri cum ar fi tinte, graffiti, etc. .. Momentan sunt prins cu alt proiect foarte important care asteapta deja de ceva timp si e prioritar acum.

**Comment by TheRealZet** [comment]
Ok, multumesc pentru raspuns (aici si pe gmail).
Succes cu proiectul!

**Comment by TheRealZet** [comment]
Iti multumesc frumos pentru raspuns, succes cu proiectul

joi, 18 iun. 2020, 00:28 Kuamquat <notifications@github.com> a scris:
