### ISSUE TITLE
Erroare skin-uri

### ISSUE THREAD

**Issue by Damigeana** [kuamquat940/csgoremake#5]
Am si eu erroare aia la skin-uri..
L 07/02/2020 - 22:40:26: -------- Mapchange to de_dust2 --------
L 07/02/2020 - 22:40:26: [csgoremake1gx.amxx] [CSGO Remake] File csgoremake1gx.ini was successfully loaded.
L 07/02/2020 - 22:40:27: [AMXX] Plugin ("csgoremake1gx.amxx") is setting itself as failed.
L 07/02/2020 - 22:40:27: [AMXX] Plugin says: [CSGO Remake] You have a missing file "-" in the [SKINS] section of csgo_remake.ini .
L 07/02/2020 - 22:40:27: [AMXX] Run time error 1 (plugin "csgoremake1gx.amxx") - forced exit

Am pus cum ai zis tu "" fara "-" si tot la fel.

**Comment by kuamquat940** [comment]
Verifica sa fie formatul cel corect, au mai fost discutii pe tema asta si pe forumul extreamcs.
